"""seeding

Revision ID: 036ef49133cb
Revises: 93ee28ab6ec3
Create Date: 2026-07-15 11:24:18.335920

"""
from typing import Sequence, Union
from models.user_model import Role
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '036ef49133cb'
down_revision: Union[str, Sequence[str], None] = '93ee28ab6ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user = str(uuid.uuid4())
user1=str(uuid.uuid4())
role=Role.patient

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
        INSERT INTO users (id, email, first_name, last_name,role_name)
        VALUES ('{user}', 'sanskruti.bhartal@coditas.com','sanskruti' ,'bhartal','patient');
    """)
    op.execute(f"""
        INSERT INTO users (id, email, first_name, last_name,role_name)
        VALUES ('{user1}', 'suyogdhage@gmail.com','suyog' ,'dhage','patient');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DELETE FROM users WHERE id = '{user}';")
    op.execute(f"DELETE FROM users WHERE id = '{user1}';")
    # ### end Alembic commands ###
