"""notification enum fix

Revision ID: 13250f720078
Revises: 86994bc40aa6
Create Date: 2026-07-14 13:58:39.621873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '13250f720078'
down_revision: Union[str, Sequence[str], None] = '86994bc40aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='notificationtype',
        new_values=['schedule', 'new_request', 'otp', 'welcome', 'panel_complete'],
        affected_columns=[TableReference(table_schema='public', table_name='notification', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='notificationtype',
        new_values=['schedule', 'new_request', 'otp', 'welcome'],
        affected_columns=[TableReference(table_schema='public', table_name='notification', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
