"""agent and panel models

Revision ID: 86994bc40aa6
Revises: 00b9cc958dce
Create Date: 2026-07-14 10:18:29.941111

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86994bc40aa6'
down_revision: Union[str, Sequence[str], None] = '00b9cc958dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('appointment_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'submitted', name='requeststatus'), nullable=True),
    sa.Column('coordinator_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('schedule', 'new_request', 'otp', 'welcome', name='notificationtype'), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['appointment_request.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('panel_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_name', sa.Enum('summarizer', name='reviewername'), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', name='reviewstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['appointment_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panel_review_request_id'), 'panel_review', ['request_id'], unique=False)
    op.create_table('panel_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('missing_items', sa.Text(), nullable=True),
    sa.Column('suggested_priority', sa.String(), nullable=True),
    sa.Column('consistency_flags', sa.Text(), nullable=True),
    sa.Column('raw_findings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['appointment_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.add_column('patient_documents', sa.Column('content', sa.Text(), nullable=True))
    # op.drop_column('patient_documents', 'chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('patient_documents', sa.Column('chunks', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True))
    op.drop_column('patient_documents', 'content')
    op.drop_table('panel_summary')
    op.drop_index(op.f('ix_panel_review_request_id'), table_name='panel_review')
    op.drop_table('panel_review')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_table('appointment_request')
    # ### end Alembic commands ###
