"""seed

Revision ID: 93ee28ab6ec3
Revises: 13250f720078
Create Date: 2026-07-15 11:22:30.213097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '93ee28ab6ec3'
down_revision: Union[str, Sequence[str], None] = '13250f720078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_documents', sa.Column('request_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'patient_documents', 'appointment_request', ['request_id'], ['id'], ondelete='SET NULL')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='requeststatus',
        new_values=['pending', 'submitted', 'processing', 'under_review', 'scheduled', 'info_needed', 'declined', 'completed'],
        affected_columns=[TableReference(table_schema='public', table_name='appointment_request', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='requeststatus',
        new_values=['pending', 'submitted'],
        affected_columns=[TableReference(table_schema='public', table_name='appointment_request', column_name='status')],
        enum_values_to_rename=[],
    )
    op.drop_constraint(None, 'patient_documents', type_='foreignkey')
    op.drop_column('patient_documents', 'request_id')
    # ### end Alembic commands ###
